/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define DATA_SIZE UINT_MAX

struct ftp_file {
	char *name;
	struct {
		u_int data_len;
		char *data_val;
	} data;
	uint64_t checksum;
};
typedef struct ftp_file ftp_file;

#define FTP_PROG 555555555
#define FTP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define READ 1
extern  ftp_file * read_1(char *, CLIENT *);
extern  ftp_file * read_1_svc(char *, struct svc_req *);
#define WRITE 2
extern  int * write_1(ftp_file , CLIENT *);
extern  int * write_1_svc(ftp_file , struct svc_req *);
#define LIST 3
extern  char ** list_1(char *, CLIENT *);
extern  char ** list_1_svc(char *, struct svc_req *);
extern int ftp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READ 1
extern  ftp_file * read_1();
extern  ftp_file * read_1_svc();
#define WRITE 2
extern  int * write_1();
extern  int * write_1_svc();
#define LIST 3
extern  char ** list_1();
extern  char ** list_1_svc();
extern int ftp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ftp_file (XDR *, ftp_file*);

#else /* K&R C */
extern bool_t xdr_ftp_file ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
