/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#define DATA_SIZE UINT_MAX

static ftp_file *
_read_1 (char * *argp, struct svc_req *rqstp)
{
	return (read_1_svc(*argp, rqstp));
}

static int *
_write_1 (ftp_file  *argp, struct svc_req *rqstp)
{
	return (write_1_svc(*argp, rqstp));
}

static char **
_list_1 (char * *argp, struct svc_req *rqstp)
{
	return (list_1_svc(*argp, rqstp));
}

static void
ftp_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *read_1_arg;
		ftp_file write_1_arg;
		char *list_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case READ:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ftp_file;
		local = (char *(*)(char *, struct svc_req *)) _read_1;
		break;

	case WRITE:
		_xdr_argument = (xdrproc_t) xdr_ftp_file;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _write_1;
		break;

	case LIST:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _list_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (FTP_PROG, FTP_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FTP_PROG, FTP_VERSION, ftp_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FTP_PROG, FTP_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FTP_PROG, FTP_VERSION, ftp_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FTP_PROG, FTP_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
