#!/usr/bin/env bash

set -e
if [ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ]; then
  cat <<-HELP
  Usage: $0
    $0 read outputFile inputFile
    $0 write inputFile outputFile
    $0 readwrite outputFile inputFile
    $0 list directory
HELP
  exit 0
fi

if [ $# -eq 2 ]; then
  java -cp ../lib/jade.jar:classes jade.Boot -gui -container -host localhost -agents "mol:AgentePunto3($1,$2)"
else
  java -cp ../lib/jade.jar:classes jade.Boot -gui -container -host localhost -agents "mol:AgentePunto3($1,$2,$3)"
fi
