/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sleeper.h"
#define foo 127

bool_t
xdr_sleeping_time (XDR *xdrs, sleeping_time *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->time))
		 return FALSE;
	return TRUE;
}
