/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SLEEPER_H_RPCGEN
#define _SLEEPER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define foo 127

struct sleeping_time {
	int time;
};
typedef struct sleeping_time sleeping_time;

#define SLEEPER_PROG 555555555
#define SLEEPER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SLEEP_TIME 1
extern  int * sleep_time_1(sleeping_time *, CLIENT *);
extern  int * sleep_time_1_svc(sleeping_time *, struct svc_req *);
extern int sleeper_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SLEEP_TIME 1
extern  int * sleep_time_1();
extern  int * sleep_time_1_svc();
extern int sleeper_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sleeping_time (XDR *, sleeping_time*);

#else /* K&R C */
extern bool_t xdr_sleeping_time ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SLEEPER_H_RPCGEN */
