/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "simp.h"
#define foo 127

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
add_1(operands *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, ADD,
		(xdrproc_t) xdr_operands, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sub_1(operands *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SUB,
		(xdrproc_t) xdr_operands, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
