all: folders matrices fib funcion instrucciones iterstruc bloques

matrices:
	gcc -o bin/matrices matrices.c
	gcc -o bin/matrices-o matrices-o.c

bloques:
	gcc -o bin/multBloques multBloques.c

fib:
	gcc -o bin/fib fib.c

funcion:
	gcc -o bin/funcion funcion.c

instrucciones:
	gcc -o bin/instrucciones instrucciones.c
	gcc -o bin/instrucciones2 instrucciones2.c

iterstruc:
	gcc -o bin/iterstruc iterstruc.c -O3

folders:
	-mkdir bin
